In [37]:
import numpy as np

In [38]:
def no_zeros(arrayInput):
    ## TODO: This function should return True if 
    ## numpy array arrayInput does not contain any zero
    ## and will return False otherwise.
    ## Implement this function using ONLY numpy methods
    ## Sample input: [1,2,3,4,5,6,0] Sample Output: False
    x = np.all(arrayInput)
    return x

In [39]:
x = np.array([34, 56, 89, 23, 69, 980,567])
print(no_zeros(x))

True


In [40]:
x = np.array([34, 56, 89, 23, 69, 980,567, 0])
print(no_zeros(x))

False


In [41]:
def linearly_distributed(n, min, max):
    ## TODO: This function should return a numpy array of
    ## length n with equally spaced elements from
    ## min (inclusive) to max (exclusive)
    ## Implement this function using ONLY numpy methods
    ## Sample input: (4,0,100) sample output [0,33,66, 99]
    x = np.linspace(min, max, n)
    return x
    #return np.array({})

    #ref: https://realpython.com/np-linspace-numpy/


In [42]:
min = 0
max = 100
n = 4
print(linearly_distributed(n, min,max))

[  0.          33.33333333  66.66666667 100.        ]


In [43]:
def two_dimensions(n):
    ## TODO: This function should create a 2d Array of shape n*n
    ## Where the borders of the array are ones
    ## all other elements are zero
    ## Implement this function using ONLY numpy methods
    ## Sample input 3
    ## sample output [[1,1,1],[1,0,1],[1,1,1]]
    x = np.ones((n,n))
    x[1:-1, 1:-1] = 0
    #return np.array({})
    return x
    #reference: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-8.php

In [44]:
n = 5
print(two_dimensions(n))

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [45]:
def create_array(n,min,max):
    ## TODO: This function should return a numpy array of
    ## length n with random elements from
    ## min (inclusive) to max (exclusive)
    ## Implement this function using ONLY numpy methods
    ## USE np.random.rand for generating the numbers
    ## Sample Input (10,0,10) sample output(0,2,2,3,1,5,9,7,8,3)
    y = np.random.randint(min, max, n)
    return y
    #return np.array({})

#Reference: https://www.programiz.com/python-programming/numpy/random#:~:text=Generate%20Random%20Array%20in%20NumPy


In [46]:
min = 1
max = 10
n = 20
# x = np.ones(n)
# print(x)
# x[0:n] = np.random.randint(min,max)
# #np.random.randint(1,10)
# print(x)


print(create_array(n,min,max))

[1 8 2 9 6 1 4 9 7 3 8 1 1 2 1 2 9 3 8 5]


In [47]:
def random_generation(n,min,max):
    ## TODO: Write a function that takes as an input
    ## Dimension of 2d Array n, min and max
    ## Generate an n*n array with random numbers between
    ## min and max inclusive
    ## Such that no element is duplicated
    ## return numpy array
    ## Implement this function using ONLY numpy methods
    ## Sample Input: random_generation(3,0,12) --> [[4,2,6],[1,5,11],[10, 3,9]]

    array = np.random.choice(np.arange(start = min, stop = max+1 , step = 1), size = (n,n), replace=False)
    return array

    #return np.array({})
    #https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html

In [48]:
min = 1
max = 6
n = 2
# x = np.ones(n)
# print(x)
# x[0:n] = np.random.randint(min,max)
# #np.random.randint(1,10)
# print(x)


print(random_generation(n,min,max))

[[3 1]
 [2 5]]
